# Site settings
title: "->C->D->E->F->"
email: curliph@gmail.com
description: >-
  AI & Agent technology for modern ASIC/SoC chip design.
baseurl: ""
url: ""
twitter_username: curliph
github_username: "0xcdef"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
